#加载mybatis配置文件
mybatis:
  #  扫描class path下mapper目录下所有.xml文件
  mapper-locations: classpath:mapper/*.xml
  # 实体类的包路径
  type-aliases-package: com.example.springvue.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      #上传单个文件的最大值
      max-file-size: 4MB
      #上传总文件的最大值
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucky?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: sch1324!/
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
